pollywogranch/config/routes.rb
Rails.application.routes.draw do

  resources :ponds

  resources :frogs

  resources :tadpoles

end

pollywogranch/app/models/frog.rb
class Frog < ActiveRecord::Base
  has_many :tadpoles
  belongs_to :pond
end

pollywogranch/app/models/pond.rb
class Pond < ActiveRecord::Base
  has_many :frogs
end

pollywogranch/app/models/tadpole.rb
class Tadpole < ActiveRecord::Base
  belongs_to :frog
end

pollywogranch/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

pollywogranch/app/controllers/frogs_controller.rb
class FrogsController < ApplicationController
  before_action :set_frog, only: [:show, :edit, :update, :destroy]

  # GET /frogs
  # GET /frogs.json
  def index
    @frogs = Frog.all
  end

  # GET /frogs/1
  # GET /frogs/1.json
  def show
  end

  # GET /frogs/new
  def new
    @frog = Frog.new
  end

  # GET /frogs/1/edit
  def edit
  end

  # POST /frogs
  # POST /frogs.json
  def create
    @frog = Frog.new(frog_params)

    respond_to do |format|
      if @frog.save
        format.html { redirect_to @frog, notice: 'Frog was successfully created.' }
        format.json { render :show, status: :created, location: @frog }
      else
        format.html { render :new }
        format.json { render json: @frog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frogs/1
  # PATCH/PUT /frogs/1.json
  def update
    respond_to do |format|
      if @frog.update(frog_params)
        format.html { redirect_to @frog, notice: 'Frog was successfully updated.' }
        format.json { render :show, status: :ok, location: @frog }
      else
        format.html { render :edit }
        format.json { render json: @frog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frogs/1
  # DELETE /frogs/1.json
  def destroy
    @frog.destroy
    respond_to do |format|
      format.html { redirect_to frogs_url, notice: 'Frog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frog
      @frog = Frog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frog_params
      params.require(:frog).permit(:name, :color)
    end
end

pollywogranch/app/controllers/ponds_controller.rb
class PondsController < ApplicationController
  before_action :set_pond, only: [:show, :edit, :update, :destroy]

  # GET /ponds
  # GET /ponds.json
  def index
    @ponds = Pond.all
  end

  # GET /ponds/1
  # GET /ponds/1.json
  def show
  end

  # GET /ponds/new
  def new
    @pond = Pond.new
  end

  # GET /ponds/1/edit
  def edit
  end

  # POST /ponds
  # POST /ponds.json
  def create
    @pond = Pond.new(pond_params)

    respond_to do |format|
      if @pond.save
        format.html { redirect_to @pond, notice: 'Pond was successfully created.' }
        format.json { render :show, status: :created, location: @pond }
      else
        format.html { render :new }
        format.json { render json: @pond.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponds/1
  # PATCH/PUT /ponds/1.json
  def update
    respond_to do |format|
      if @pond.update(pond_params)
        format.html { redirect_to @pond, notice: 'Pond was successfully updated.' }
        format.json { render :show, status: :ok, location: @pond }
      else
        format.html { render :edit }
        format.json { render json: @pond.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponds/1
  # DELETE /ponds/1.json
  def destroy
    @pond.destroy
    respond_to do |format|
      format.html { redirect_to ponds_url, notice: 'Pond was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pond
      @pond = Pond.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pond_params
      params.require(:pond).permit(:name)
    end
end

pollywogranch/app/controllers/tadpoles_controller.rb
class TadpolesController < ApplicationController
  before_action :set_tadpole, only: [:show, :edit, :update, :destroy]

  # GET /tadpoles
  # GET /tadpoles.json
  def index
    @tadpoles = Tadpole.all
  end

  # GET /tadpoles/1
  # GET /tadpoles/1.json
  def show
  end

  # GET /tadpoles/new
  def new
    @tadpole = Tadpole.new
  end

  # GET /tadpoles/1/edit
  def edit
  end

  # POST /tadpoles
  # POST /tadpoles.json
  def create
    @tadpole = Tadpole.new(tadpole_params)

    respond_to do |format|
      if @tadpole.save
        format.html { redirect_to @tadpole, notice: 'Tadpole was successfully created.' }
        format.json { render :show, status: :created, location: @tadpole }
      else
        format.html { render :new }
        format.json { render json: @tadpole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tadpoles/1
  # PATCH/PUT /tadpoles/1.json
  def update
    respond_to do |format|
      if @tadpole.update(tadpole_params)
        format.html { redirect_to @tadpole, notice: 'Tadpole was successfully updated.' }
        format.json { render :show, status: :ok, location: @tadpole }
      else
        format.html { render :edit }
        format.json { render json: @tadpole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tadpoles/1
  # DELETE /tadpoles/1.json
  def destroy
    @tadpole.destroy
    respond_to do |format|
      format.html { redirect_to tadpoles_url, notice: 'Tadpole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tadpole
      @tadpole = Tadpole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tadpole_params
      params.require(:tadpole).permit(:name, :color)
    end
end

pollywogranch/app/helpers/application_helper.rb
module ApplicationHelper
end

pollywogranch/app/helpers/frogs_helper.rb
module FrogsHelper
end

pollywogranch/app/helpers/ponds_helper.rb
module PondsHelper
end

pollywogranch/app/helpers/tadpoles_helper.rb
module TadpolesHelper
end

pollywogranch/app/views/frogs/_form.html.erb
<%= form_for(@frog) do |f| %>
  <% if @frog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frog.errors.count, "error") %> prohibited this frog from being saved:</h2>

      <ul>
      <% @frog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pollywogranch/app/views/frogs/edit.html.erb
<h1>Editing frog</h1>

<%= render 'form' %>

<%= link_to 'Show', @frog %> |
<%= link_to 'Back', frogs_path %>

pollywogranch/app/views/frogs/index.html.erb
<h1>Listing frogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frogs.each do |frog| %>
      <tr>
        <td><%= frog.name %></td>
        <td><%= frog.color %></td>
        <td><%= link_to 'Show', frog %></td>
        <td><%= link_to 'Edit', edit_frog_path(frog) %></td>
        <td><%= link_to 'Destroy', frog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frog', new_frog_path %>

pollywogranch/app/views/frogs/new.html.erb
<h1>New frog</h1>

<%= render 'form' %>

<%= link_to 'Back', frogs_path %>

pollywogranch/app/views/frogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @frog.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @frog.color %>
</p>

<%= link_to 'Edit', edit_frog_path(@frog) %> |
<%= link_to 'Back', frogs_path %>

pollywogranch/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollywogranch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

pollywogranch/app/views/ponds/_form.html.erb
<%= form_for(@pond) do |f| %>
  <% if @pond.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pond.errors.count, "error") %> prohibited this pond from being saved:</h2>

      <ul>
      <% @pond.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pollywogranch/app/views/ponds/edit.html.erb
<h1>Editing pond</h1>

<%= render 'form' %>

<%= link_to 'Show', @pond %> |
<%= link_to 'Back', ponds_path %>

pollywogranch/app/views/ponds/index.html.erb
<h1>Listing ponds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ponds.each do |pond| %>
      <tr>
        <td><%= pond.name %></td>
        <td><%= link_to 'Show', pond %></td>
        <td><%= link_to 'Edit', edit_pond_path(pond) %></td>
        <td><%= link_to 'Destroy', pond, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pond', new_pond_path %>

pollywogranch/app/views/ponds/new.html.erb
<h1>New pond</h1>

<%= render 'form' %>

<%= link_to 'Back', ponds_path %>

pollywogranch/app/views/ponds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pond.name %>
</p>

<%= link_to 'Edit', edit_pond_path(@pond) %> |
<%= link_to 'Back', ponds_path %>

pollywogranch/app/views/tadpoles/_form.html.erb
<%= form_for(@tadpole) do |f| %>
  <% if @tadpole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tadpole.errors.count, "error") %> prohibited this tadpole from being saved:</h2>

      <ul>
      <% @tadpole.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pollywogranch/app/views/tadpoles/edit.html.erb
<h1>Editing tadpole</h1>

<%= render 'form' %>

<%= link_to 'Show', @tadpole %> |
<%= link_to 'Back', tadpoles_path %>

pollywogranch/app/views/tadpoles/index.html.erb
<h1>Listing tadpoles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tadpoles.each do |tadpole| %>
      <tr>
        <td><%= tadpole.name %></td>
        <td><%= tadpole.color %></td>
        <td><%= link_to 'Show', tadpole %></td>
        <td><%= link_to 'Edit', edit_tadpole_path(tadpole) %></td>
        <td><%= link_to 'Destroy', tadpole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tadpole', new_tadpole_path %>

pollywogranch/app/views/tadpoles/new.html.erb
<h1>New tadpole</h1>

<%= render 'form' %>

<%= link_to 'Back', tadpoles_path %>

pollywogranch/app/views/tadpoles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tadpole.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @tadpole.color %>
</p>

<%= link_to 'Edit', edit_tadpole_path(@tadpole) %> |
<%= link_to 'Back', tadpoles_path %>